### ISSUE TITLE
diet4j NoClassDefFoundError

### ISSUE THREAD

**Issue by Amir-Sela** [diet4j/diet4j#18]
Hi ! I created a jar and I was trying to load it dynamic with diet4j cmdline and diet4j didn't find my jar 
ModuleRunException: Module: org.example:bleicher-test:1.0-SNAPSHOT, cannot execute run method main in class Main
	at org.diet4j.core.Module.run(Module.java:400)
	at org.diet4j.cmdline.CmdlineBootLoader.activateRunDeactivate(CmdlineBootLoader.java:305)
	at org.diet4j.cmdline.CmdlineBootLoader.main(CmdlineBootLoader.java:71)
Caused by: java.lang.NoClassDefFoundError: BigBleicher
	at Main.main(Main.java:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.diet4j.core.Module.run(Module.java:379)
	... 2 more
Caused by: java.lang.ClassNotFoundException: BigBleicher (ClassLoader for module org.example:bleicher-test:1.0-SNAPSHOT)
	at org.diet4j.core.ModuleClassLoader.loadClass(ModuleClassLoader.java:312)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 8 more

with this pom:
```
<dependencies>
         <dependency>
           <groupId>org.example</groupId>
           <artifactId>big-bleicher</artifactId>
           <version>1.0-SNAPSHOT</version>
           <scope>provided</scope>
       </dependency>
       <dependency>
           <groupId>org.apache.logging.log4j</groupId>
           <artifactId>log4j-api</artifactId>
           <version>2.13.3</version>
       </dependency>
       <dependency>
           <groupId>org.apache.logging.log4j</groupId>
           <artifactId>log4j-core</artifactId>
           <version>2.13.3</version>
       </dependency>
```
   </dependencies>

**Comment by jernst** [comment]
``provided``? diet4j will ignore those.
